kubefin/kubefin

README.md

Fixes #none
* Update readme to add highlights.
```release-note
```

doc: Update readme to add highlights

---

config_template/third_party/mimir_config.yaml

Fixes #6 
There isn't perfect way to fix it, just make it better now.
* support big cpu/memory metrics query
```release-note
```

performance: Support big CPU and memory metrics queries

---

.github/workflows/kubefin-devel-release.yaml

Fixes #none
* Add latest image build and yaml release
```release-note
```

ci: add devel KubeFin release

---

.github/workflows/kubefin-devel-release.yaml

Fixes #none
* Fix devel image release workflow
```release-note
```

ci: fix devel image release

---

.github/workflows/kubefin-devel-release.yaml
README.md
hack/local-start-kubefin.sh
hack/release-yamls.sh
hack/utils.sh

Fixes #none
* ko doesn't support latest tag with `--tag-only`, so I changed it to devel
```release-note
```

ci: update latest image tag to devel

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md

Fixes #none
* Update feature request template and bug reporting template
```release-note
```

doc: Update feature request template and bug reporting template

---

.github/workflows/kubefin-release.yaml

Fixes #none
* ci: fix dashboard release workflow
```release-note
```

ci: fix dashboard release workflow

---

config_template/core/deployments/kubefin-cost-analyzer.yaml
hack/local-start-kubefin.sh

Fixes #none
* bug: fix release yaml
```release-note
```

bug: fix release yaml

---

dashboard/web/src/common/network/http-common.js

Fixes #none
* fix request url for api 
```release-note
```

fix: fix request url for api

---

.github/workflows/kubefin-e2e.yaml

Fixes #none
* ci: setup workflow to launch KubeFin testing env
```release-note
```

ci: setup workflow to launch KubeFin testing env

---

.github/workflows/kubefin-devel-release.yaml
.github/workflows/kubefin-e2e.yaml
.github/workflows/kubefin-release.yaml

Fixes #none
*  ci: build linux/arm64 images 
```release-note
```

ci: build linux/arm64 images

---

pkg/api/analyzer_types.go
pkg/cloudprice/ack/provider.go
pkg/cloudprice/ack/types.go
pkg/cloudprice/apis/price.go
pkg/cloudprice/eks/provider.go
pkg/cloudprice/provider.go

Fixes #2 
* support eks clusters
*
*
```release-note
```

[WIP] feat: support eks clusters

---

.github/workflows/kubefin-devel-release.yaml
.github/workflows/kubefin-release.yaml

Fixes #none
* ci: add arm64 image build
```release-note
```

ci: add arm64 image build

---

hack/cherry_pick_pull.sh

Fixes #11 
*
*
*
```release-note
```

support cherry-pick automatically with one script

---

api/docs.go
api/swagger.json
api/swagger.yaml
dashboard/web/src/pages/dashboard/components/cluster-cost/cluster-cost-overview.jsx
pkg/api/agent_types.go
pkg/cloudprice/ack/provider.go
pkg/cloudprice/defaultcloud/provider.go
pkg/metrics/core/node_metrics.go
pkg/utils/metrics_collect.go

Fixes #none
* fix per core price calculation
* Update swagger files
* Update dashboard typo
```release-note
`kubefin-agent`: fix per core average price calculation
```

fix: fix per core average price calculation

---

cmd/kubefin-agent/app/options/options.go
config_template/core/deployments/kubefin-agent.yaml
pkg/metrics/agent_metrics.go
pkg/metrics/cache/usage_cache.go
pkg/metrics/core/node_metrics.go
pkg/metrics/core/pod_metrics.go
pkg/metrics/core/workload_metrics.go
pkg/utils/common.go
pkg/utils/metrics_collect.go
pkg/values/default.go

Fixes #
* improve metrics query performance
```release-note
`kubefin-agent`: Improve metrics query performance.
```

performance: improve metrics query performance

---

.github/workflows/kubefin-e2e.yaml
config_template/third_party/mimir.yaml
config_template/third_party/mimir_config.yaml

Fixes #44 
* fix mimir CrashLoopBackOff
```release-note
`mimir`: fix mimir CrashLoopBackOff.
```

bug: fix mimir CrashLoopBackOff

---

config_template/core/deployments/kubefin-agent.yaml
hack/local-start-kubefin.sh
hack/utils.sh

Fixes #
* Fix the `IAMGE` typo
* Add necessary tool checks for installation
* Avoid accidental failure to obtain the server’s IP and Port

improve the `local-start-kubefin.sh` scripts

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/api/analyzer_types.go
pkg/router/router.go
pkg/server/implementation/cluster_metrics.go
pkg/server/metrics_handler/cluster_details.go
pkg/server/metrics_handler/cluster_summary.go
test/e2e/clusters_summary_test.go
test/e2e/utils/e2e_values.go
test/e2e/utils/validation.go

Fixes #none
* feat: make the API more explicit.
```release-note
`kubefin-core`: Change `/api/v1/metrics/...` to `/api/v1/resources/...`, it's more explicit for the query result.
```

feat: make the API more explicit

---

config_template/core/300-customworkloadinsight/knative-serving.yaml
config_template/core/300-customworkloadinsight/kubeflow-job.yaml

Add kubeflow customAllocationConfiguration
**release-note**
```release-note
`kubefin-core`: Support customAllocationConfiguration for kubeflow.
```

add kubeflow customAllocationConfiguration

---

config_template/third_party/mimir_config.yaml
pkg/metrics/core/node_metrics.go
pkg/metrics/core/pod_metrics.go
pkg/metrics/core/workload_metrics.go
pkg/query/prom_client.go
pkg/query/promql.go
pkg/server/implementation/cluster_metrics.go
pkg/server/metrics_handler/cluster_details.go
pkg/utils/common.go
pkg/utils/metrics_collect.go
pkg/values/metrics.go

Fixes https://github.com/kubefin/kubefin/issues/28
* fix: filter pod with Success/Error phase
```release-note
`kubefin-core`: filter out pods with a Success/Error phase.
```

fix: filter out pods with a Success/Error phase.

---

dashboard/web/src/pages/dashboard/components/all-clusters/AllClustersDashboard.js
hack/release-yamls.sh
pkg/router/router.go
pkg/server/resources_handler/cluster_details.go
pkg/server/resources_handler/cluster_summary.go

Fixes #none
* ci: fix devel release workflow
```release-note
```

ci: fix devel release workflow

---

config_template/core/deployments/kubefin-agent.yaml
dashboard/web/src/pages/dashboard/components/all-clusters/clusters-table-list.jsx
dashboard/web/src/pages/dashboard/components/cluster-cost/cluster-cost-header.jsx
dashboard/web/src/pages/dashboard/components/model/cluster-compute-cost.jsx
dashboard/web/src/pages/dashboard/components/model/namespace/namespace-cost.jsx
dashboard/web/src/pages/dashboard/components/namespace-cost/namespace-cost-header.jsx
dashboard/web/src/pages/dashboard/components/table/cluster-compute-cost-list-item.jsx
dashboard/web/src/pages/dashboard/components/table/cluster-compute-cost-list.jsx
dashboard/web/src/pages/dashboard/components/table/ns-cost-table-list.jsx
dashboard/web/src/pages/dashboard/components/table/table-property-filter-config.jsx
pkg/server/implementation/workload_cost.go

Fixes #none
* bug: fix dashboard memory insights
```release-note
`kubefin`: Fix cluster memory allocation insights.
```

bug: fix dashboard memory insights

---

OWNERS

Fixes #none
* feat: add owner file of KubeFin
```release-note
```

feat: add owner file of KubeFin

---

Makefile
hack/build-images.sh
hack/build.sh
hack/dockerfiles/Dockerfile
hack/dockerfiles/buildx.Dockerfile
hack/utils.sh
hack/version.sh
pkg/version/base.go
pkg/version/version.go

add makefile to build image

---

pkg/cloudprice/ack/provider.go

Fixes #
*
*
*
```release-note
```

cleanup: make parts code clean

---

dashboard/web/src/pages/dashboard/components/cluster-cost/compute-cost-chart.jsx
dashboard/web/src/pages/dashboard/components/single-cluster/cluster-cpu-utilization.jsx
dashboard/web/src/pages/dashboard/components/single-cluster/cluster-memory-utilization.jsx

Fixes #none
* cleanup: make dashbaord chart easier to understand
```release-note
```

cleanup: make dashbaord chart easier to understand

---

dashboard/web/src/pages/dashboard/components/namespace-cost/namespace-cost-header.jsx
dashboard/web/src/pages/dashboard/components/workload-cost/table-config.jsx

Fixes #none
* cleanup: Make the fields of the dashboard more accurate
```release-note
```

cleanup: Make the fields of the dashboard more accurate

---

config_template/core/300-customworkloadinsight/argo-workflow.yaml

Fixes https://github.com/kubefin/kubefin/issues/54
* feat: support argo workflow cost insights
```release-note
`kubefin-core`: support argo workflow cost insights.
```

feat: support argo workflow cost insights

---

pkg/analyzer/server/costs_handler/cluster_resource.go
pkg/analyzer/server/costs_handler/cluster_summary.go
pkg/analyzer/server/costs_handler/cluster_workload.go
pkg/analyzer/server/resources_handler/cluster_details.go
pkg/analyzer/server/resources_handler/cluster_summary.go

Fixes #none
* cleanup: make the log level unified
```release-note
```

cleanup: make the log level unified

---

.github/workflows/kubefin-e2e.yaml
DEVELOPMENT.md
README.md
config_template/core/100-namespace.yaml
config_template/core/200-roles/role.yaml
config_template/core/200-serviceaccount.yaml
config_template/core/configmap/otel.yaml
config_template/core/deployments/kubefin-agent.yaml
config_template/core/deployments/kubefin-cost-analyzer.yaml
config_template/third_party/grafana.yaml
config_template/third_party/grafana_config.yaml
config_template/third_party/mimir.yaml
config_template/third_party/mimir_config.yaml
hack/local-start-kubefin.sh
hack/utils.sh
pkg/values/default.go

Change kubefin to kubefin-system

---

.github/workflows/kubefin-devel-release.yaml

Fixes #none
* ci: add devel yaml release to aws s3
```release-note
```

ci: upload devel yaml release to aws s3

---

.github/workflows/kubefin-devel-release.yaml

Fixes #none
* cleanup: fix ci workflow
```release-note
```

cleanup: fix ci workflow

---

.github/workflows/kubefin-devel-release.yaml

Fixes #none
* ci: fix upload release yaml failure
```release-note
```

ci: fix upload release yaml failure

---

.github/workflows/kubefin-devel-release.yaml

Fixes #none
* ci: use official aws cli action
```release-note
```

ci: use official aws cli action

---

.github/workflows/kubefin-devel-release.yaml

Fixes #none
* ci: only upload the necessary yaml
```release-note
```

ci: only upload the necessary yaml

---

.github/workflows/kubefin-devel-release.yaml

Fixes #none
* ci: upload single file
```release-note
```

ci: upload single file

---

pkg/agent/cloudprice/provider.go

Fixes #none
* fix: record the cloud provider correctly
```release-note
`kubefin-core`: fix the mistake of recording cloud provider.
```

fix: record the cloud provider correctly

---

DEVELOPMENT.md

Fixes #none
* doc: cleanup development doc
```release-note
```

doc: cleanup development doc

---

dashboard/web/src/pages/dashboard/components/all-clusters/clusters-cost-overview.jsx
dashboard/web/src/pages/dashboard/components/cluster-cost/cluster-cost-overview.jsx
dashboard/web/src/pages/dashboard/components/cluster-cost/compute-cost-chart.jsx
dashboard/web/src/pages/dashboard/components/table/cluster-compute-cost-list.jsx
dashboard/web/src/pages/dashboard/components/table/ns-cost-table-list.jsx
dashboard/web/src/pages/dashboard/components/table/table-property-filter-config.jsx

Fixes #none
* cleanup: support for higher precision data display
```release-note
```

cleanup: support for higher precision data display

---

pkg/agent/metrics/core/pod_metrics.go
pkg/agent/types/types.go
pkg/agent/utils/utils.go

Fixes #none
* fix: do not record the cost for the success/failed pod
```release-note
`kubefin-core`: Do not record the cost for the success/failed pod
```

fix: do not record the cost for the success/failed pod

---

pkg/agent/cloudprice/ack/provider.go
pkg/agent/cloudprice/eks/provider.go

Fixes #none
* fix: calculate the node core/gib hourly price correctly
```release-note
`kubefin-core`: calculate the node core/gib hourly price correctly
```

fix: calculate the node core/gib hourly price correctly

---

pkg/agent/cloudprice/ack/provider.go
pkg/agent/cloudprice/apis/node.go
pkg/agent/utils/utils.go

Fixes #none
* cleanup: clean parts code to make it better
```release-note
```

cleanup: clean parts code to make it better

---

dashboard/web/src/pages/dashboard/components/cluster-cost/cluster-cost-overview.jsx

Fixes #none
* cleanup: fix the avg core daily cost display
```release-note
```

cleanup: fix the avg core daily cost display

---

dashboard/web/src/pages/dashboard/components/all-clusters/clusters-cost-overview.jsx

Fixes #none
* dashboard: fix typo of cluster cost
```release-note
```

dashboard: fix typo of cluster cost

---

.github/workflows/kubefin-go-build.yaml
hack/utils.sh

Fixes #none
* cleanup: fix makefile building failure
```release-note
```

cleanup: fix makefile building failure

---

README.md

Fixes #none
* doc: update slack channel link
```release-note
```

doc: update slack channel link
